name = input("Enter Full Name :")
phone = input ("Enter mobile number :")
byear = input ("Enter birth of year :")
print(name)
# print(phone)
phone = phone.split("-")
print(phone)
age = 2023 - int(byear)
print(age)
